# --- FONT ---
font_family                 JetBrainsMono Nerd Font
font_size                   13.0

# --- WINDOW ---
remember_window_size        no
initial_window_width        1050
initial_window_height       600
window_padding_width        10
confirm_os_window_close     0

# --- CURSOR ---
cursor_blink_interval       0.5
wheel_scroll_min_lines      1

# --- HISTORY AND AUDIO ---
scrollback_lines            2000
enable_audio_bell           no

# --- APPEARANCE ---
background_opacity          0.9

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
