# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = JetBrainsMono Nerd Font

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250
    }
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 4
    blur_size = 10
    color = rgba(0, 0, 0, 0.6)
}

input-field {
    monitor =
    size = 320, 60
    outline_thickness = 2
    inner_color = rgba(255, 255, 255, 0.05)
    outer_color = rgba(255, 255, 255, 0.1)
    check_color = rgba(255, 255, 255, 0.3)
    fail_color = rgba(255, 100, 100, 0.5)
    font_color = rgb(240, 240, 240)
    fade_on_empty = false
    rounding = -1

    shadow_passes = 2
    shadow_size = 4
    shadow_color = rgba(0, 0, 0, 0.8)

    font_family = $font
    placeholder_text = <i>Enter Password...</i>
    fail_text = <b>$PAMFAIL</b>

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3
    dots_center = true

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -100
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    font_size = 110
    font_family = $font ExtraBold
    color = rgba(255, 255, 255, 0.9)

    shadow_passes = 2
    shadow_size = 4
    shadow_color = rgba(0, 0, 0, 0.8)

    position = 0, 100
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    font_size = 22
    font_family = $font
    color = rgba(220, 220, 220, 0.8)

    shadow_passes = 2
    shadow_size = 3
    shadow_color = rgba(0, 0, 0, 0.8)

    position = 0, -10
    halign = center
    valign = center
}
