#Import files

source = ~/.config/hypr/modules/autostart.conf
source = ~/.config/hypr/modules/programs.conf
source = ~/.config/hypr/modules/env_variables.conf
source = ~/.config/hypr/modules/permissions.conf
source = ~/.config/hypr/modules/style.conf
source = ~/.config/hypr/modules/input.conf
source = ~/.config/hypr/modules/keybindings.conf
source = ~/.config/hypr/modules/workspace.conf
source = ~/.config/hypr/modules/dms.conf


source = ./dms/cursor.conf
