#################
### AUTOSTART ###
#################

# Autostart necessary processes
exec-once = systemctl --user start hyprpolkitagent
exec-once = udiskie
# exec-once = nm-applet --indicator
exec-once = dms run
