# DMS / Quickshell Configuration

# windowrule = float on, match:class ^(org.quickshell)$
layerrule = no_anim on, match:namespace ^(quickshell)$
layerrule = no_anim on, match:namespace ^dms:.*

# Sources
# Nota: Questi file devono esistere nella cartella 'dms' all'interno di ~/.config/hypr/
source = ~/.config/hypr/dms/colors.conf
source = ~/.config/hypr/dms/layout.conf
source = ~/.config/hypr/dms/binds.conf
source = ~/.config/hypr/dms/cursor.conf
source = ~/.config/hypr/dms/outputs.conf
source = ~/.config/hypr/dms/windowrules.conf
