
###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
$fileManager = thunar
$rofiDir = ~/.config/rofi/launchers/type-2
$menu = rofi -show drun -theme $rofiDir/style-menu.rasi
$powermenu = ~/.config/hypr/scripts/powermenu.sh
$clipboard = cliphist list | rofi -dmenu -p "Clipboard " -theme $rofiDir/style-clipboard.rasi | cliphist decode | wl-copy

