# --- THEME ---
[general]
import = ["~/.cache/wal/colors-alacritty.toml"]

# --- WINDOW ---
[window]
opacity = 0.9
dynamic_padding = true

# --- FONT ---
[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"
